spring.application.name=API-siglab
# ===============================
# DATASOURCE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/siglab_db
spring.datasource.username=postgres
spring.datasource.password=Math270603@

spring.flyway.locations=classpath:db/migrations
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# FLAYWAY
# ===============================
spring.flyway.locations=classpath:db/migrations